#' @title Plot Log-Log Test for Proportional Hazards Hypothesis
#'
#' @description This function uses the return from the Kaplan-Meier model
#' to create a log-log plot. It calculates log(-log(Survival Probability))
#' and log(Time).
#'
#' @param surv_plot Survival plot generated by `plot_survival`.
#' @inheritParams plot_survival
#' @return Log-log plot.
#' @keywords internal

plot_loglog <- function(km,
                        vaccinated_status,
                        unvaccinated_status) {
  # Calculate log-variables
  km$loglog <- log(-log(km$surv))
  km$logtime <- log(km$time)

  # Plot colors
  vaccinated_color <- "steelblue"
  unvaccinated_color <- "darkred"

  # Plot
  plt_loglog <- ggplot2::ggplot(data = km) +
    ggplot2::geom_step(ggplot2::aes(x = .data$logtime,
                                    y = .data$loglog,
                                    color = .data$strata)
    ) +
    ggplot2::theme_classic() +
    ggplot2::labs(x = "Log[Time to event] (Days)",
                  y = "Log[-Log[Surv.]]") +
    ggplot2::labs(colour = "Vaccine Status") +
    ggplot2::scale_color_manual(
      name = "Vaccine Status",
      values = c(vaccinated_color, unvaccinated_color),
      labels = c(vaccinated_status, unvaccinated_status)
    )
  return(plt_loglog)
}

#' @title Plot the Survival Probability Based on the Kaplan-Meier Model
#'
#' @description This function relies on the implementation of the Kaplan-Meier
#' model from the package `{survival}`. It returns a plot of the Survival
#' Probability or the Cumulative Hazard (if cumulative = TRUE).
#' The return is a ggplot2 element of the curves with 95% C.I. It is possible
#' to manipulate the colors, labels, legend, and most of the graphic elements.
#'
#' @importFrom rlang .data
#' @inheritParams effectiveness
#' @param vaccinated_color Color assigned to the vaccinated population.
#' @param unvaccinated_color Color assigned to the unvaccinated population.
#' @param percentage If `TRUE`, returns probability in percentage.
#' @param cumulative If `TRUE`, returns cumulative hazards.
#' @return `{ggplot2}` object with plot of survival or cumulative incidence.
#' @examples
#' # Define start and end dates of the study
#' start_cohort <- as.Date("2044-01-01")
#' end_cohort <- as.Date("2044-12-31")
#'
#' # Create `data.frame` with information on immunization
#' cohortdata <- make_immunization(
#'   data = cohortdata,
#'   outcome_date_col = "death_date",
#'   censoring_date_col = "death_other_causes",
#'   immunization_delay = 14,
#'   vacc_date_col = "vaccine_date_2",
#'   end_cohort = end_cohort
#' )
#'
#' # Match the data
#' matching <- match_cohort(
#'   data = cohortdata,
#'   outcome_date_col = "death_date",
#'   censoring_date_col = "death_other_causes",
#'   start_cohort = start_cohort,
#'   end_cohort = end_cohort,
#'   method = "static",
#'   exact = "sex",
#'   nearest = c(age = 1)
#' )
#'
#' # Extract matched data
#' cohortdata_match <- dataset(matching)
#'
#' # Plot survival curve
#' plot_survival(
#'   data = cohortdata_match,
#'   start_cohort = start_cohort,
#'   end_cohort = end_cohort
#' )
#' @export

plot_survival <- function(data,
                          start_cohort,
                          end_cohort,
                          outcome_status_col = "outcome_status",
                          time_to_event_col = "time_to_event",
                          vacc_status_col = "vaccine_status",
                          vaccinated_status = "v",
                          unvaccinated_status = "u",
                          vaccinated_color = "steelblue",
                          unvaccinated_color = "darkred",
                          percentage = TRUE,
                          cumulative = FALSE) {
  # input checking
  checkmate::assert_data_frame(
    data,
    min.rows = 1L
  )
  checkmate::assert_names(
    names(data),
    must.include = c(outcome_status_col, time_to_event_col, vacc_status_col)
  )
  checkmate::assert_character(
    c(vaccinated_color, unvaccinated_color)
  )
  checkmate::assert_logical(
    percentage,
    len = 1
  )
  checkmate::assert_logical(
    cumulative,
    len = 1
  )
  # check date types
  checkmate::assert_date(
    start_cohort,
    any.missing = FALSE, len = 1
  )
  checkmate::assert_date(
    end_cohort,
    any.missing = FALSE, len = 1
  )
  checkmate::assert_names(
    data[[vacc_status_col]],
    must.include = c(vaccinated_status, unvaccinated_status)
  )

  # KM model
  km <- km_model(data = data,
    outcome_status_col = outcome_status_col,
    time_to_event_col = time_to_event_col,
    vacc_status_col = vacc_status_col,
    vaccinated_status = vaccinated_status,
    unvaccinated_status = unvaccinated_status,
    start_cohort = start_cohort,
    end_cohort = end_cohort
  )

  if (cumulative) {
    km$plot <- km$cumincidence
    km$plot_lower <- km$cumincidence_lower
    km$plot_upper <- km$cumincidence_upper
  } else {
    km$plot <- km$surv
    km$plot_lower <- km$upper
    km$plot_upper <- km$lower
  }

  # set colour names for vaccination status
  colors <- c(vaccinated_color, unvaccinated_color)
  vacc_status <- c(vaccinated_status, unvaccinated_status)
  names(colors) <- c(vaccinated_status, unvaccinated_status)

  plt <-
    ggplot2::ggplot(data = km) +
    ggplot2::geom_ribbon(
      ggplot2::aes(
        x = .data$time,
        ymin = .data$plot_lower, ymax = .data$plot_upper,
        fill = .data$strata
      ),
      alpha = 0.2
    ) +
    ggplot2::geom_step(
      ggplot2::aes(
        x = .data$time, y = .data$plot,
        color = .data$strata
      )
    ) +
    ggplot2::scale_y_continuous(
      labels = ifelse(
        test = percentage, yes = scales::label_percent(),
        no = scales::label_number()
      )
    ) +
    ggplot2::scale_color_manual(
      name = "Vaccine Status",
      values = colors,
      labels = vacc_status
    ) +
    ggplot2::scale_fill_manual(
      name = "Vaccine Status",
      values = colors,
      labels = vacc_status
    ) +
    ggplot2::theme_classic() +
    ggplot2::labs(
      x = "Time to event (Days)",
      y = ifelse(
        cumulative, yes = "Cumulative incidence", no = "Survival probability"
      )
    ) +
    ggplot2::xlab("Time to event (Days)") +
    ggplot2::labs(colour = "Vaccine Status")

  return(plt)
}
